#!/bin/bash

#SBATCH --job-name=eval
#SBATCH --output=eval_log/qwen2_5omni_baseline_sharegpt_tedlium-whisper-5-best-with-audio
#SBATCH --error=eval_log/qwen2_5omni_baseline_sharegpt_tedlium-whisper-5-best-with-audio
#SBATCH --ntasks=1
#SBATCH --time=04:00:00
#SBATCH --mem=200G
#SBATCH --nodes=1
#SBATCH --partition=grizzly,polar,polar3,polar4
#SBATCH --account=nvr_taiwan_rvos
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=8
#SBATCH --overcommit

source /home/zwan/.cache/conda/etc/profile.d/conda.sh
conda activate qwen_eval

#default_model="/lustre/fsw/portfolios/nvr/users/hanrongy/checkpoints/xvila/xvila-nvila_8b-video_audBoostv2_s3_n8_bs2048_ga8_mstep-1_j20250414/model"
#default_output_dir="./eval_output"
#default_log_dir="./eval_log"
cd ~/.cache/LLaMA-Factory
#llamafactory-cli train examples/train_lora/qwen2_5omni_lora_sft.yaml
CUDA_VISIBLE_DEVICES=0 python test_qwen.py "tedlium" "1470" "False"
