import json
import os
from transformers.models.whisper.english_normalizer import BasicTextNormalizer
normalizer = BasicTextNormalizer()
import sys
import random

SPEECH_HANDS_DATA = os.environ.get("SPEECH_HANDS_DATA", "./data")
SPEECH_HANDS_OUTPUT = os.environ.get("SPEECH_HANDS_OUTPUT", "./output")



def get_prompt(internal_pred, flamingo_list, question, options_str, ckpt):
    #v2 prompt
#     prompt = f"""You are an Audio Understanding model with access to three inputs:

# (1) The original audio;
# (2) Five answer hypotheses from an external model;
# (3) Your own answer prediction based on the audio alone (internal).

# Your task is to:
# - First decide whether your internal answer is confident and correct.
# - If yes, output <no_ref> and the correct answer.
# - If not, output <need_ref> and re-answer the question using both the audio and the external hypotheses.

# Question: {question}
# Options:
# {options_str}

# External model 5-best predictions:
# {flamingo_list}

# Internal prediction: {internal_pred}

#     """
# v3 prompt
#     - If your internal prediction is correct and acceptable, output <internal> and repeat your answer.
# - If the external top-1 candidate is correct while your internal prediction is incorrect, output <external> and use the external answer.
# - If both your internal and external top-1 are incorrect, but a better answer can be inferred from the full list and audio, output <rewrite> and revise the answer.

# v4 prompt
# - If your internal prediction is trustworthy and matches the audio and question, output <internal> and repeat your answer.
# - If the external top-1 candidate seems more accurate or plausible, output <external> and use it.
# - If neither seems clearly correct, but the audio and external candidates offer useful clues, output <rewrite> and revise the answer.

    if ckpt == "v4":
        prompt = f"""You are an audio understanding model with access to three inputs:

(1) The original audio;
(2) Five answer candidates generated by another model (external);
(3) Your own prediction (internal).

Your task is to decide which of the following strategies to apply:
- If your internal prediction is trustworthy and matches the audio and question, output <internal> and repeat your answer.
- If the external top-1 candidate seems more accurate or plausible, output <external> and use it.
- If neither seems clearly correct, but the audio and external candidates offer useful clues, output <rewrite> and revise the answer.

Return the selected token (<internal>/<external>/<rewrite>) followed by your final answer.

Question: {question}
Options:
{options_str}

External model 5-best predictions:
{flamingo_list}

Internal prediction: {internal_pred}

"""

    if ckpt == "v3":
        prompt = f"""You are an audio understanding model with access to three inputs:

(1) The original audio;
(2) Five answer candidates generated by another model (external);
(3) Your own prediction (internal).

Your task is to decide which of the following strategies to apply:
- If your internal prediction is correct and acceptable, output <internal> and repeat your answer.
- If the external top-1 candidate is correct while your internal prediction is incorrect, output <external> and use the external answer.
- If both your internal and external top-1 are incorrect, but a better answer can be inferred from the full list and audio, output <rewrite> and revise the answer.

Return the selected token (<internal>/<external>/<rewrite>) followed by your final answer.

Question: {question}
Options:
{options_str}

External model 5-best predictions:
{flamingo_list}

Internal prediction: {internal_pred}

"""
    if ckpt == "v5":
        prompt = f"""You are an audio understanding model with access to three inputs:

(1) The original audio;
(2) Five answer candidates generated by another model (external);
(3) Your own prediction (internal).

Your task is to decide which of the following strategies to apply:
- If your internal prediction is correct and acceptable, output <internal> and repeat your answer.
- If the external top-1 candidate is correct while your internal prediction is incorrect, output <external> and use the external answer.
- If your internal prediction is incorrect, but external hypotheses (2–5) contain the correct answer, output <rewrite_guided> and rewrite based on that useful information.
- If all given answers are incorrect, output <rewrite_free> and re-answer the question correctly based only on the original audio.

Return the selected token (<internal>/<external>/<rewrite_guided>/<rewrite_free>) followed by your final answer.

Question: {question}
Options:
{options_str}

External model 5-best predictions:
{flamingo_list}

Internal prediction: {internal_pred}

"""

    if "1best" in ckpt:
        prompt = f"""You are an audio understanding model with access to three inputs:

(1) The original audio;
(2) One answer candidate generated by another model (external);
(3) Your own prediction (internal).

Your task is to decide which of the following strategies to apply:
- If your internal prediction is correct and acceptable, output <internal> and repeat your answer.
- If the external candidate is correct while your internal prediction is incorrect, output <external> and use the external answer.
- If all given answers are incorrect, output <rewrite> and re-answer the question correctly based only on the original audio.

Return the selected token (<internal>/<external>/<rewrite>) followed by your final answer.

Question: {question}
Options:
{options_str}

External model 1-best predictions:
{flamingo_list}

Internal prediction: {internal_pred}

"""

    return prompt.strip() + "\n\n"

def acc(pred, gold):
    if type(pred) == list:
        for pred in pred:
            if normalizer(pred) == normalizer(gold):
                return 1
        return 0
    else:
        return 1 if normalizer(pred) == normalizer(gold) else 0

subset = sys.argv[1]
ckpt = sys.argv[2]

with open(f"{SPEECH_HANDS_DATA}/dcase_audioqa/2025_{subset}_sharegpt.json", "r") as f:
    question_data = json.load(f)

with open(f"{SPEECH_HANDS_OUTPUT}/2025/with_audio_ckpt-baseline_{subset}/output.json", "r") as f:
    qwen_data = json.load(f)

with open(f"{SPEECH_HANDS_OUTPUT}/2025/with_audio_ckpt-flamingo_{subset}/output.json", "r") as f:
    nbest_data = json.load(f)

with open(f"{SPEECH_HANDS_OUTPUT}/2025/with_audio_ckpt-flamingo-5best_{subset}/output.json", "r") as f:
    top_5_data = json.load(f)

qwen_correct_1best_wrong = 0
qwen_correct_1best_correct = 0
qwen_wrong_1best_correct = 0
qwen_wrong_1best_wrong = 0


num_internal = 0
num_external = 0
num_rewrite = 0

output_data = []
for i in range(len(question_data)):
    if "part3" in ckpt and f"{subset}/audio" not in nbest_data[i]['audio']:
        continue
    if "part2" in ckpt and f"{subset}/fold" not in nbest_data[i]['audio']:
        continue
    if "part1" in ckpt and (f"{subset}/audio" in qwen_data[i]['audio'] or f"{subset}/fold" in qwen_data[i]['audio']):
        continue
    

    # print(qwen_data[i]['audio'])
    # if not "train/audio" in qwen_data[i]['audio']:
    #     continue
    # if not "train/fold" in qwen_data[i]['audio']:
    #     continue

    assert qwen_data[i]['audio'] == nbest_data[i]['audio']
    # string to list
    # print(question_data[i]['conversations'][0]['value'])
    options = question_data[i]['conversations'][0]['value'].split("Choices:")[1].split("\n-")
    options = [option.strip() for option in options if option!=""]
    # print(options)
    # assert len(options) == 4 or len(options) == 3
    
    ok = 0
    for option in options:
        if normalizer(qwen_data[i]['pred']) == normalizer(option):
            qwen_data[i]['pred'] = option
            ok = 1
            break

    if ok == 0:
        print(qwen_data[i]['pred'], options)
        

    assert normalizer(qwen_data[i]['gold']) == normalizer(nbest_data[i]['gold'])
    qwen_acc = acc(qwen_data[i]['pred'], qwen_data[i]['gold'])
    nbest_1best_acc = acc(nbest_data[i]['pred'], nbest_data[i]['gold'])
    nbest_5best_acc = acc(top_5_data[i]['pred'], top_5_data[i]['gold'])
    # print(qwen_acc, nbest_acc)


    if qwen_acc == 1:
        question_data[i]["conversations"][1]["value"] = "<internal> " + question_data[i]['conversations'][1]['value']
        num_internal += 1
        if nbest_1best_acc == 1:
            qwen_correct_1best_correct += 1
        else:
            qwen_correct_1best_wrong += 1

    else:
        if nbest_1best_acc == 1:
            question_data[i]["conversations"][1]["value"] = "<external> " + question_data[i]['conversations'][1]['value']
            num_external += 1
            qwen_wrong_1best_correct += 1
        else:
            if "part3" in ckpt:
                # 50% probability to add rewrite
                # if random.random() < 0.5:
                # for pred in top_5_data[i]['pred']:
                if nbest_5best_acc == 1:
                    num_external += 1
                    question_data[i]["conversations"][1]["value"] = "<external> " + question_data[i]['conversations'][1]['value']
                else:
                    num_rewrite += 1
                    question_data[i]["conversations"][1]["value"] = "<rewrite> " + question_data[i]['conversations'][1]['value']
            else:
                num_rewrite += 1
                question_data[i]["conversations"][1]["value"] = "<rewrite> " + question_data[i]['conversations'][1]['value']

            qwen_wrong_1best_wrong += 1
            
    question_data[i]["conversations"][0]["value"] = get_prompt(qwen_data[i]['pred'], nbest_data[i]['pred'], question_data[i]['conversations'][0]['value'].split("Question:")[1].split("Choices:")[0].strip(), question_data[i]['conversations'][0]['value'].split("Choices:")[1], ckpt)
    # if compute_wer(baseline_pred, gold) == 0 or compute_wer(baseline_pred, gold) < best_wer:
    output_data.append(question_data[i])

    # print(question_data[i])
    # assert False

with open(f"{SPEECH_HANDS_DATA}/dcase_audioqa/2025_{subset}_sharegpt_rag_{ckpt}.json", "w") as f:
    json.dump(output_data, f, indent=1)

print("num_internal", num_internal)
print("num_external", num_external)
print("num_rewrite", num_rewrite)

print("qwen_correct_1best_correct", qwen_correct_1best_correct)
print("qwen_correct_1best_wrong", qwen_correct_1best_wrong)
print("qwen_wrong_1best_correct", qwen_wrong_1best_correct)
print("qwen_wrong_1best_wrong", qwen_wrong_1best_wrong)


